### ISSUE TITLE
TRADFRI bulb GU10 WS 345lm, color problem.

### ISSUE THREAD

**Issue by marktn** [zigbeefordomoticz/z4d-certified-devices#54] opened 2024-02-29 18:01 UTC
TRADFRI bulb GU10 WS 345lm
https://www.ikea.com/nl/nl/p/tradfri-led-lamp-gu10-345-lumen-smart-draadloos-dimbaar-gekleurd-en-wit-spectrum-80439228/
This model is not Optimized.
 Plugin: 7.1.008 [4.215] 

The problem is, when changing the color, it is not changing always.  
Only after 2 times switching it On, it sets to the right color.

I did a test: Light off, Light On color White, Light Off,  Light On color Warm (does not work, color stays white), Light On color Warm (works).

[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14451767/export.json)

**Comment by pipiche38** [comment] 2024-02-29 18:21
Is that happening for the 3 Bulbs you have ?
I just pushed a config file you'll need to come to [4.229]

**Comment by marktn** [comment] 2024-02-29 18:55
It happens on 2 Bulbs, i did not test it on the other Bulbs.
I will update and test it.

**Comment by marktn** [comment] 2024-02-29 19:06
Problem is the same after update. Or should i repair?

![afbeelding](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/11601535/6ef1e399-2086-4de5-9372-dc62e2ecc375)

**Comment by pipiche38** [comment] 2024-03-13 19:56
As discuss on keybase, the issue is related to the fact that the plugin is going beyond mirred temperature range.
It will be fixed with 7.1.010

**Closed by pipiche38** 2024-03-13 19:56 UTC
