### ISSUE TITLE
[Model Certification] - Tuya Human Presence Detector

### ISSUE THREAD

**Issue by Snake40** [zigbeefordomoticz/z4d-certified-devices#11] opened 2023-10-15 13:44 UTC
1. Tuya Human Presence Detector 5.8GHz Ceiling Mount ZY-M100-2 (ceiling version)
2. https://fr.aliexpress.com/item/1005005543432442.html?spm=a2g0o.order_list.order_list_main.41.1a115e5bq0BIvj&gatewayAdapt=glo2fra
3. At this stage, the detector is seen by the zigbeefordomoticz plugin (device not optimized) but no device is reported in Domoticz
4. Raw Devices (json)
{"PluginInfos":{"HardwareID":7,"HomeFolder":"/opt/domoticz/userdata/plugins/Domoticz-Zigbee/","StartupFolder":"/opt/domoticz/","UserDataFolder":"/opt/domoticz/userdata/","WebRoot":"","Database":"/opt/domoticz/userdata/domoticz.db","Language":"fr","Version":"6.3","Author":"pipiche38","Name":"Zigbee","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/ttyACM0","Key":"Zigate","Mode1":"ZigpyEZSP","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode6":"2","DomoticzVersion":"2023.2 (build 15555)","DomoticzHash":"94ed578b5","DomoticzBuildTime":"2023-09-18 11:18:01","PluginBranch":"stable6","PluginVersion":"6.3.012","TimeStamp":1697377395,"available":0,"available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"6.10.3.0 build 297","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":true,"CoordinatorModel":"Unknown Silicon Labs","DisplayFirmwareVersion":"UNK - 6.10.3.0 build 297","CoordinatorIEEE":"e0798dfffe71910c","NetworkSize":"Total: 24 | Routers: 7 | End Devices: 17","NetworkDevices":{"1002":{"_TZE200_b6wax7g0":["TS0601-_TZE200_b6wax7g0"],"_TYZB01_ftdkanlj":["TS0222"],"_TZ3000_dowj6gyi":["TS0201"]},"1141":{"_TZ3000_gjnozsaz":["TS011F-plug"],"_TZ3000_dowj6gyi":["TS0201"],"_TZ3000_tqlv4ug4":["TS0001"]}}},"Analytics":0,"Device":{"Version":"3","ZDeviceName":"","Status":"UNKNOW","SQN":"2a","Ep":{"01":{"0000":{"0004":"_TZE204_sxm7l9xa","0000":"3","0001":"74","0005":"TS0601","0007":"1","fffe":"0","ffe2":"56","ffe4":"0","ffdf":"湾,eǹ,i˹,i̹,iι,iֹ,i׹,i幾,f"}},"f2":{}},"Heartbeat":"565","RIA":"6","LQI":152,"Battery":{},"Model":"TS0601","ForceAckCommands":[],"MacCapa":"8e","IEEE":"a4c1388fa92ff4d8","Type":{},"ProfileID":{},"ZDeviceID":{},"App Version":"74","Attributes List":{},"DeviceType":"FFD","HW Version":"","Last Cmds":[],"LogicalType":"Router","Manufacturer":"","Manufacturer Name":"_TZE204_sxm7l9xa","NbEp":"2","PowerSource":"Main","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1697374553,"iSQN":{"0004":"00","0000":"00","0001":"00","0005":"00","0007":"00","fffe":"00"},"Attributes":{"0004":"00","0000":"00","0001":"00","0005":"00","0007":"00","fffe":"00","ffe2":"00","ffe4":"00","ffdf":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"","Stack Version":"","Stamp":{"time":1697377398.808149,"Time":"2023-10-15 15:43:18","MsgType":"8011","LastSeen":1697377398},"ZCL Version":"3","Health":"Live","Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"ZCLSQN":"00","ZDPSQN":"01","ZCL-IN-SQN":{"ef00":"2a","000a":"cf","0000":"21"},"RollingLQI":[152,152,156,156,156,152,152,152,152,152,152],"WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"Epv2":{"01":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}},"f2":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}}},"PairingInProgress":true,"SQN_000a":"cf","ConsistencyCheck":"Bad Pairing"}}

**Comment by pipiche38** [comment] 2023-10-15 15:37
stable6 is not supported , so please upgrade to stable7

Check here for more information
https://easydomoticz.com/forum/viewtopic.php?p=114383#p114383

when on a running 7.1.004 (which is the latest)

move to a dedicated branch

`git checkout device-integration-human-presence-detector`


restart the plugin and redo the pairing

**Comment by pipiche38** [comment] 2023-10-21 17:24
Any update ?
Can we get logs please enable the debug 'TuyaTS0601' and 'Tuya' parameters

**Comment by pipiche38** [comment] 2023-11-02 17:44
Ordered from Tuya. Waiting for delivery

**Comment by pipiche38** [comment] 2023-11-08 14:48
duplicate of #22

**Closed by pipiche38** 2023-11-08 14:48 UTC
Labels: Looking for feedback/confirmation
