### ISSUE TITLE
[TS0601] - Tuya - Human Presence Detector 5.8GHz Wall Mount

### ISSUE THREAD

**Issue by bartw91** [zigbeefordomoticz/z4d-certified-devices#22] opened 2023-11-07 13:57 UTC
i'm trying to add: [Human Presence Detector 5.8GHz Wall Mount](https://zigbee.blakadder.com/Tuya_ZY-M100-S.html), but i keep getting adopting error.

Log:
[errors (3).json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13280670/errors.3.json)

![adopt](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/111068907/0db1b077-d82d-4e07-82dd-ebe574071b48)

Can you help me @pipiche38

**Comment by pipiche38** [comment] 2023-11-08 13:55
I have order one, to do the proper intégration.
In between you might want to look after that one https://github.com/zigbeefordomoticz/z4d-certified-devices/issues/11#issuecomment-1763426782

which is a duplicate of #22

**Comment by bartw91** [comment] 2023-11-08 14:01
I did the: git checkout device-integration-human-presence-detector
But stil get the same result when trying to pair the device.

**Comment by pipiche38** [comment] 2023-11-08 14:04
did you authorize Device creation in Domoticz ?

**Comment by bartw91** [comment] 2023-11-08 14:06
Yes that is enabled

**Comment by pipiche38** [comment] 2023-11-08 14:47
so please provides the logs from Domoticz and from plugin (Logs/PluginZigbee_xx.log ) not only the error log

**Comment by bartw91** [comment] 2023-11-08 15:19
Domoticz log:
2023-11-08 16:15:25.182 Error: Zigbee : processNotinDBDevices - Creat Domo Device Failed !!! for 9bae status: 8043

Plugin log:
[PluginZigbee_log_error_history_48.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13298332/PluginZigbee_log_error_history_48.json)

![1](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/111068907/1522fd18-eded-4cd8-8d8f-ff7b93f4bd89)

**Comment by pipiche38** [comment] 2023-11-08 16:17
can you try the following:

1) remove all domoticz widgets related to that devices ( you can eventually search for a4c138842331bea3 in the domoticz widgets )
2) remove it from the Plugin Device list if still theer
3) update the plugin by```

git pull
git checkout wip-stable7-1-005
git pull
sudo python3 -m pip install -r requirements.txt --upgrade

4) restart the plugin and do the pairing
```

**Comment by bartw91** [comment] 2023-11-08 16:28
Its getting better.

![3](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/111068907/55e633d4-cda8-4932-992c-843d7a2006bc)
![2](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/111068907/7826dd8b-ec7d-472d-99a9-7621c09cc57c)

Domoticz log:
2023-11-08 17:23:23.768 Error: Zigbee : Decode 8041 - Receive an IEEE: a4c138842331bea3 with a NwkId: 024c, seems not known by the plugin
2023-11-08 17:23:24.784 Error: Zigbee : Decode 8041 - Receive an IEEE: a4c138842331bea3 with a NwkId: 024c, seems not known by the plugin
2023-11-08 17:23:51.859 Error: Zigbee : Receiving a leave from c76d/a4c138842331bea3 while device is Leave status
2023-11-08 17:23:51.916 Error: Zigbee : Receiving a leave from c76d/a4c138842331bea3 while device is Leave status

Motion is not being detected

**Comment by pipiche38** [comment] 2023-11-08 17:30
can you do an update 

```
git pull
sudo python3 -m pip install -r requirements.txt --upgrade
```

and simply restart the plugin

**Comment by bartw91** [comment] 2023-11-08 18:01
Yes it works now, thank you!

**Comment by pipiche38** [comment] 2023-11-08 18:12
Thanks for your support and the logs. Shame that the previous one didn't came with the logs, it would have prevented me to purchase that device !

Please feel free to close the issue if happy

**Closed** 2023-11-08 18:15 UTC
